name: Validate PR
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
#       if: (github.head_ref == 'master) || 
      run: echo {{ github.head_ref }}
