name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.1
        extensions: mbstring
        coverage: xdebug
      
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules/
          ./vendor/
        key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}-${{ hashFiles('package*.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        npm ci
      
    - name: PHPUnit tests
      run: |
        ./vendor/bin/phpunit phptests

    - run: ./node_modules/.bin/jest
