name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PHPUnit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.4
        extensions: mbstring
        coverage: xdebug

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./vendor/
        key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: PHPUnit tests
      run: ./vendor/bin/phpunit phptests --log-junit junit.xml

    - name: Parse junit files
      if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
      uses: DarkHole1/phpunit-junit-action@v0.0.2
      with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules/
        key: ${{ runner.os }}-${{ hashFiles('package*.json') }}-v2

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - uses: DarkHole1/eslint-action@master
      # GITHUB_TOKEN in forked repositories is read-only
      if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        source-root: ./src/
        node-root: ../node_modules

    - name: JS tests
      continue-on-error: true
      run: ./node_modules/.bin/jest --ci --reporters=default --reporters=jest-junit

    - uses: IgnusG/jest-report-action@master
      if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
